apiVersion: v1
kind: Service
metadata:  # 修正箇所
  name: hello-server-external
spec:
  type: NodePort
  selector:
    app: hello-server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30599  # nodePortのポート番号の指定は必須
